export type TestRunScope = 'focused' | 'full';
export type TestRunStatus = 'requested' | 'running' | 'passed' | 'failed' | 'timed_out' | 'blocked' | 'invalid_request';
export interface VerificationRunRow { run_id: string; request_id: string; task_id: string | null; target_command: string; scope: TestRunScope; timeout_seconds: number; requester_identity: string; requested_at: string; status: TestRunStatus; exit_code: number | null; duration_ms: number; metrics_json: string | null; stdout_digest: string | null; stderr_digest: string | null; stdout_excerpt: string | null; stderr_excerpt: string | null; completed_at: string | null; }
export type CommandEnvPolicy = { mode: 'inherit' } | { mode: 'allowlist'; names: string[] } | { mode: 'empty' };
export type CommandStdinPolicy = { mode: 'none' } | { mode: 'inline'; digest: string } | { mode: 'artifact'; artifact_uri: string; digest: string };
export type CommandSideEffectClass = 'read_only' | 'workspace_write' | 'external_write' | 'network' | 'process_control' | 'long_running_server' | 'gui_open' | 'destructive';
export type CommandApprovalPosture = 'not_required' | 'required' | 'approved' | 'rejected';
export type CommandOutputAdmissionProfile = 'digest_only' | 'bounded_excerpt' | 'artifact_retained';
export type CommandRunStatus = 'requested' | 'rejected' | 'approved' | 'running' | 'succeeded' | 'failed' | 'timed_out' | 'cancelled' | 'blocked_by_policy';
export interface CommandRunRow { run_id: string; request_id: string; requester_id: string; requester_kind: 'operator' | 'agent' | 'system'; command_argv: string[]; command_argv_json: string; cwd: string; env_policy: CommandEnvPolicy; env_policy_json: string; timeout_seconds: number; stdin_policy: CommandStdinPolicy; stdin_policy_json: string; task_id: string | null; task_number: number | null; agent_id: string | null; side_effect_class: CommandSideEffectClass; approval_posture: CommandApprovalPosture; output_admission_profile: CommandOutputAdmissionProfile; idempotency_key: string; requested_at: string; rationale: string | null; status: CommandRunStatus; exit_code: number | null; signal: string | null; started_at: string | null; completed_at: string | null; duration_ms: number | null; stdout_digest: string | null; stderr_digest: string | null; stdout_admitted_excerpt: string | null; stderr_admitted_excerpt: string | null; full_output_artifact_uri: string | null; error_class: string | null; approval_outcome: CommandApprovalPosture; telemetry_json: string | null; updated_at: string; }
export type RepoPublicationStatus = 'prepared' | 'pushed' | 'failed' | 'abandoned';
export interface RepoPublicationRow { publication_id: string; repo_root: string; branch: string; remote: string; commit_hash: string; base_ref: string | null; bundle_path: string; patch_path: string | null; task_number: number | null; requester_id: string; requested_at: string; status: RepoPublicationStatus; pushed_at: string | null; confirmed_by: string | null; confirmation_json: string | null; failure_reason: string | null; updated_at: string; }
